### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by crespoter**
Removed the testimonial and blog part and added the team page

### CODE REVIEW

**Comment by SriHarshaGajavalli** [comment]
Can you provide some description on why do we need these changes?

**Comment by crespoter** [comment]
Removed the testimonial and blog part and added the team page

**Comment by SriHarshaGajavalli** [comment]
Firstly, we need the blog and testimonials to be there on the front page. Though there aren't any as of now, let's keep the empty sections for now.

Coming to the team page, it needs to be a seperate html page.

With this, I don't see there is any need for this PR. I want to hear your justifications for this PR

**Comment by crespoter** [comment]
The blog and testimonial are only commented out, we can have them included when we have any of those. 
The team section would provide a brief intro to the team and would redirect to the main team page from there.

**Comment by SriHarshaGajavalli** [comment]
That's perfectly fine.

In my view, it is always to have, though they are empty sections, so that people who see the website understand what we are going to add to the website. if you really want to make it more lively, we can write a few blogs and collect testimonials from our previous workshop attendees and add them. I would suggest not to comment them out.

Coming to the team page, let's not keep anything on the main for now. Once the organization team stabilizes well enough, we can think of it.

**Comment by crespoter** [comment]
Okay. I am closing this PR

**Pull request closed without merging**
