### PR TITLE
Makeover for website

### PR DESCRIPTION
**Pull request by FermatsLastAccount**
Changed how the landing page looked, added transparent logos, changed the background image to match the colour scheme, added a logo in the navigation bar, added sponsor logos, changed how the three lines appeared in the view, revised a few content holders.

### CODE REVIEW

**Comment by soham1705** [comment]
Hi @FermatsLastAccount 
I really like the background, the navbar and landing screen logos, and the sponsor logos. However, the landing screen text and icons are not fitting on the screen (in my browser, at least). Also, the 'View our works' button is missing. I am attaching some screenshots. Please review.

sketch 5

sketch 6

**Comment by FermatsLastAccount** [comment]
Thanks for your feedback :))
Do we really need the view our works button on our landing? We do have a "projects" tab for the same in our navbar. 

Sure thing, will look into what is causing the problem.

**Comment by soham1705** [comment]
Let the button be there, but rename it to something else if you feel the name is not appropriate. It makes for easy navigation.

**Comment by SriHarshaGajavalli** [comment]
@soham1705 @crespoter: Merging this as it fixes issue #33 

New issues will be opened soon

**Pull request merged**
