### PR TITLE
Updated landing page

### PR DESCRIPTION
**Pull request by FermatsLastAccount**
Fixed responsiveness (that's what I believe, tested on two different screens and by changing window size)
Changed "What our sponsors say"
Unable to add the arrow button, working on it.

### CODE REVIEW

**Comment by SriHarshaGajavalli** [comment]
@FermatsLastAccount: Unfortunately, this is not completely responsive. Need to look once again.

Coming to the sponsor, those are not the requested changes in pull #45. So closing this PR for now. Feel free to make a new PR or reopen this considering the feedback

**Comment by FermatsLastAccount** [comment]
No problem :))
Would you please provide me with screenshots so as to where my code breaks?
Also, would you get me up to speed on what are you expecting from the responsive landing page?

**Comment by SriHarshaGajavalli** [comment]
selection_099

**Comment by SriHarshaGajavalli** [comment]
It should work perfectly well on mobile screens (consider a 5 inch phone as a minimum screen size)

**Comment by FermatsLastAccount** [comment]
was it working on mobile phones before my makeover PR?
I was facing problems with the size of the text we used while working on it. As you can see, the logo scaled down perfectly, but the text didn't

**Comment by SriHarshaGajavalli** [comment]
To my knowledge, yes, it was working. However, I think it will be good if
we decrease the font size (even for the laptop screens)





*Sri Harsha Gajavalli*
*B.Tech - 3rd Year*
*Computer Science and Engineering*
*IIIT Chittoor*
*Sri City-517588*
*(+91)-91007 53548*

**Comment by chhanganivarun** [comment]
Also @FermatsLastAccount the logo and text aren't at the expected position even in laptop view.
And a small thing, in the contact us email i.d., the link should be mailto: aidevelopercommunity@gmail.com
instead of mailto: contact@example.com

**Pull request closed without merging**
